# Generated by Django 4.0.1 on 2022-01-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(verbose_name='Об Ассоциации')),
                ('mission', models.TextField(verbose_name='Миссия и ценности')),
            ],
            options={
                'verbose_name': 'Об Ассоциации',
                'verbose_name_plural': 'Об Ассоциации',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название отчета')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('report_text', models.TextField(verbose_name='Отчет')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('signature', models.TextField(blank=True, null=True, verbose_name='Должность Ф.И.О. подпись')),
                ('add_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='Supervisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=70, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Отчество')),
                ('company_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Названии компании')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/photos')),
                ('add_info', models.TextField(verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Член наблюдательного совета',
                'verbose_name_plural': 'Члены наблюдательного совета',
            },
        ),
    ]
