# Generated by Django 4.0.1 on 2022-04-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_aboutpictures_documentspol_alter_documents_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Об Ассоциации_en'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Об Ассоциации_kg'),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок_en'),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='subtitle_kg',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок_kg'),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст_en'),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='text_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст_kg'),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tекст_en'),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='text_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст_kg'),
        ),
    ]
