# Generated by Django 4.0.1 on 2022-04-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_alter_aboutus_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название документа'),
        ),
        migrations.AddField(
            model_name='documents',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название документа_en'),
        ),
        migrations.AddField(
            model_name='documents',
            name='name_kg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название документа_kg'),
        ),
        migrations.AddField(
            model_name='documentspol',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название документа'),
        ),
        migrations.AddField(
            model_name='documentspol',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название документа_en'),
        ),
        migrations.AddField(
            model_name='documentspol',
            name='name_kg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название документа_kg'),
        ),
    ]
