# Generated by Django 4.0.1 on 2022-04-19 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0005_remove_submit_company_members_and_more'),
        ('about_us', '0004_reports_add_info_en_reports_add_info_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founders',
            name='founder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='submit.submit', verbose_name='Выберите из Члены  АКИ или уже выбран чтобы посмотреть нажмите на карандаш'),
        ),
    ]
