# Generated by Django 4.0.1 on 2022-02-27 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0003_remove_submit_company_socials_submit_facebook_and_more'),
        ('association_member', '0003_alter_members_photo'),
        ('about_us', '0004_remove_supervisory_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisory',
            name='submit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='submit.submit'),
        ),
        migrations.AlterField(
            model_name='supervisory',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='association_member.members'),
        ),
    ]
