# Generated by Django 4.0.1 on 2022-04-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_documents_name_documents_name_en_documents_name_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='add_info_en',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация_en'),
        ),
        migrations.AddField(
            model_name='reports',
            name='add_info_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация_kg'),
        ),
        migrations.AddField(
            model_name='reports',
            name='name_en',
            field=models.TextField(blank=True, null=True, verbose_name='Название отчета_en'),
        ),
        migrations.AddField(
            model_name='reports',
            name='name_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Название отчета_kg'),
        ),
        migrations.AddField(
            model_name='reports',
            name='short_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание_en'),
        ),
        migrations.AddField(
            model_name='reports',
            name='short_description_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание_kg'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Название отчета'),
        ),
    ]
