# Generated by Django 4.0.1 on 2022-02-27 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association_member', '0003_alter_members_photo'),
        ('about_us', '0005_supervisory_submit_alter_supervisory_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisory',
            name='submit',
        ),
        migrations.AlterField(
            model_name='supervisory',
            name='add_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.CreateModel(
            name='Founders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/photos', verbose_name='Фото руководителя')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('founder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='association_member.members')),
            ],
            options={
                'verbose_name': 'Учредители Ассоциации',
                'verbose_name_plural': 'Учредители Ассоциации',
            },
        ),
    ]
