# Generated by Django 4.0.1 on 2022-02-28 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association_member', '0003_alter_members_photo'),
        ('about_us', '0006_remove_supervisory_submit_alter_supervisory_add_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founders',
            name='founder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='association_member.members', verbose_name='Выберите из Члены  АКИ или уже выбран чтобы посмотреть нажмите на карандаш'),
        ),
        migrations.AlterField(
            model_name='supervisory',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='association_member.members', verbose_name='Выберите из Члены  АКИ или уже выбран чтобы посмотреть нажмите на карандаш'),
        ),
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=300, verbose_name='Заголовка')),
                ('text', models.TextField(verbose_name='Текст')),
                ('about_us', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about_us.aboutus')),
            ],
            options={
                'verbose_name': 'Почему ценно быть членов АКИ',
                'verbose_name_plural': 'Почему ценно быть членов АКИ',
            },
        ),
    ]
