# Generated by Django 4.0.1 on 2022-02-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0007_alter_founders_founder_alter_supervisory_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Цели на год',
                'verbose_name_plural': 'Цели на год',
            },
        ),
    ]
