# Generated by Django 4.0.1 on 2022-02-28 10:59

import about_us.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0008_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_doc', models.FileField(upload_to='static/document/%d/%m/%Y', validators=[about_us.validators.validate_file_extension], verbose_name='Устав')),
                ('politic_doc', models.FileField(upload_to='static/document/%d/%m/%Y', validators=[about_us.validators.validate_file_extension], verbose_name='Учетная политика')),
            ],
            options={
                'verbose_name': 'Устав, Учетная политика',
            },
        ),
    ]
