# Generated by Django 4.0.1 on 2022-02-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First name')),
                ('e_mail', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100, verbose_name='Phone number')),
                ('message_text', models.TextField(verbose_name='Your comment')),
                ('message_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
