# Generated by Django 4.0.1 on 2022-02-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submit',
            old_name='e_mail',
            new_name='company_email',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='message_date',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='message_text',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='submit',
            name='company_activity',
            field=models.CharField(max_length=500, null=True, verbose_name='Company activity'),
        ),
        migrations.AddField(
            model_name='submit',
            name='company_field',
            field=models.CharField(max_length=500, null=True, verbose_name='Company field'),
        ),
        migrations.AddField(
            model_name='submit',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/logo'),
        ),
        migrations.AddField(
            model_name='submit',
            name='company_members',
            field=models.IntegerField(blank=True, null=True, verbose_name='Company members'),
        ),
        migrations.AddField(
            model_name='submit',
            name='company_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Company name'),
        ),
        migrations.AddField(
            model_name='submit',
            name='company_phone',
            field=models.CharField(max_length=100, null=True, verbose_name='Company phone number'),
        ),
        migrations.AddField(
            model_name='submit',
            name='company_reg_date',
            field=models.CharField(max_length=50, null=True, verbose_name='Company registration date'),
        ),
        migrations.AddField(
            model_name='submit',
            name='company_socials',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Company social pages'),
        ),
        migrations.AddField(
            model_name='submit',
            name='company_webpage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company webpage'),
        ),
        migrations.AddField(
            model_name='submit',
            name='full_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='submit',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Position in company'),
        ),
    ]
