# Generated by Django 4.0.1 on 2022-02-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_rename_e_mail_submit_company_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='company_socials',
        ),
        migrations.AddField(
            model_name='submit',
            name='facebook',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='submit',
            name='instagram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='submit',
            name='telegram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='submit',
            name='tiktok',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='submit',
            name='twitter',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='submit',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='company_activity',
            field=models.CharField(max_length=500, null=True, verbose_name='Деятельность компании'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='company_email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='company_field',
            field=models.CharField(max_length=500, null=True, verbose_name='Креативная отрасль компании'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/logo', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='company_members',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество сотрудников'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='company_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='company_phone',
            field=models.CharField(max_length=100, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='company_reg_date',
            field=models.DateField(max_length=50, null=True, verbose_name='Дата регистрации компании/ИП '),
        ),
        migrations.AlterField(
            model_name='submit',
            name='company_webpage',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Сайт компании/ИП'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='full_name',
            field=models.CharField(max_length=100, null=True, verbose_name='ФИО руководителя'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность руководителя'),
        ),
    ]
