# Generated by Django 4.0.1 on 2022-04-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_alter_submit_company_webpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='company_webpage',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Сайт компании/ИП'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='facebook',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Facebook'),
        ),
    ]
