# Generated by Django 4.0.1 on 2022-04-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0003_alter_submit_company_webpage_alter_submit_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='instagram',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='telegram',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='tiktok',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='TikTok'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='twitter',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Twitter'),
        ),
    ]
