# Generated by Django 4.0.1 on 2022-04-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0004_alter_submit_instagram_alter_submit_telegram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='company_members',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='company_reg_date',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='company_webpage',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='whatsapp',
        ),
        migrations.AlterField(
            model_name='submit',
            name='company_activity',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Деятельность компании'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='company_field',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Креативная отрасль компании'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='company_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон'),
        ),
    ]
