# Generated by Django 4.0.1 on 2022-03-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E mail')),
                ('telephone', models.CharField(max_length=100, verbose_name='Phone number')),
                ('address', models.TextField(verbose_name='Address')),
                ('telegram', models.CharField(max_length=150, verbose_name='Telegram')),
                ('instagram', models.CharField(max_length=150, verbose_name='Instagram')),
                ('facebook', models.CharField(max_length=150, verbose_name='Facebook')),
                ('copyright', models.CharField(max_length=200, verbose_name='Copyright')),
                ('studio_name', models.CharField(max_length=200, verbose_name='Studio')),
            ],
            options={
                'verbose_name': 'Наш Контакт',
                'verbose_name_plural': 'Наши Контакты',
            },
        ),
    ]
