# Generated by Django 4.0.1 on 2022-03-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(verbose_name='Текст описания')),
                ('advantages', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Преимущества и краткая информация',
                'verbose_name_plural': 'Главная страница',
            },
        ),
    ]
