# Generated by Django 4.0.1 on 2022-04-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='advantages_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='advantages_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='Текст описания'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='Текст описания'),
        ),
    ]
