# Generated by Django 4.0.1 on 2022-02-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Преимущества и краткая информация', 'verbose_name_plural': 'Главная страница'},
        ),
    ]
