# Generated by Django 4.0.1 on 2022-04-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='short_description_eng',
            field=models.TextField(blank=True, null=True, verbose_name='Текст описания Eng'),
        ),
    ]
