# Generated by Django 4.0.1 on 2022-04-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_mainpage_short_description_eng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Аддрес')),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('whatsapp', models.CharField(blank=True, max_length=150, null=True, verbose_name='WhatsApp')),
                ('facebook', models.URLField(blank=True, max_length=150, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, max_length=150, null=True, verbose_name='instagram')),
                ('twitter', models.URLField(blank=True, max_length=150, null=True, verbose_name='Twitter')),
                ('tiktok', models.URLField(blank=True, max_length=150, null=True, verbose_name='TikTok')),
                ('telegram', models.URLField(blank=True, max_length=150, null=True, verbose_name='Telegram')),
            ],
            options={
                'verbose_name': 'Футер',
                'verbose_name_plural': 'Футер',
            },
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='short_description_eng',
        ),
    ]
