# Generated by Django 4.0.1 on 2022-01-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=70, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=70, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/photos')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Краткая биография')),
            ],
            options={
                'verbose_name': 'Член ассоциаций',
                'verbose_name_plural': 'Члены ассоциации',
            },
        ),
        migrations.CreateModel(
            name='RulesAndPolitics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_to', models.TextField(verbose_name='Как стать членом ассоциаций')),
                ('politics', models.TextField(blank=True, null=True, verbose_name='Устав и членская политика')),
            ],
            options={
                'verbose_name': 'Устав и членская политика',
                'verbose_name_plural': 'Устав и членская политика',
            },
        ),
    ]
