# Generated by Django 4.0.1 on 2022-03-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesAndPolitics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_to', models.TextField(verbose_name='Как стать членом ассоциаций')),
            ],
            options={
                'verbose_name': 'Как стать членом ассоциаций',
                'verbose_name_plural': 'Как стать членом ассоциаций',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/members', verbose_name='Фото руководителя')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Краткая биография')),
                ('submit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submit', to='submit.submit', verbose_name='Выберите из ЗАЯВКИ или уже выбран чтобы посмотреть нажмите на карандаш')),
            ],
            options={
                'verbose_name': 'Члены ассоциаций',
                'verbose_name_plural': 'Члены ассоциации',
            },
        ),
    ]
