# Generated by Django 4.0.1 on 2022-02-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association_member', '0002_alter_members_options_remove_members_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/members', verbose_name='Фото руководителя'),
        ),
    ]
