# Generated by Django 4.0.1 on 2022-02-28 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0003_remove_submit_company_socials_submit_facebook_and_more'),
        ('association_member', '0003_alter_members_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='submit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submit', to='submit.submit', verbose_name='Выберите из ЗАЯВКИ или уже выбран чтобы посмотреть нажмите на карандаш'),
        ),
    ]
