# Generated by Django 4.0.1 on 2022-02-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association_member', '0004_alter_members_submit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rulesandpolitics',
            options={'verbose_name': 'Как стать членом ассоциаций', 'verbose_name_plural': 'Как стать членом ассоциаций'},
        ),
        migrations.RemoveField(
            model_name='rulesandpolitics',
            name='politics',
        ),
    ]
