# Generated by Django 4.0.1 on 2022-04-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeproject',
            name='name_en',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название статьи_en'),
        ),
        migrations.AddField(
            model_name='creativeproject',
            name='name_kg',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название статьи_kg'),
        ),
        migrations.AddField(
            model_name='creativeproject',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст статьи_en'),
        ),
        migrations.AddField(
            model_name='creativeproject',
            name='text_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст статьи_kg'),
        ),
        migrations.AddField(
            model_name='formalregistrations',
            name='name_en',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название статьи_en'),
        ),
        migrations.AddField(
            model_name='formalregistrations',
            name='name_kg',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название статьи_kg'),
        ),
        migrations.AddField(
            model_name='formalregistrations',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст статьи_en'),
        ),
        migrations.AddField(
            model_name='formalregistrations',
            name='text_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст статьи_kg'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_en',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название статьи_en'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_kg',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название статьи_kg'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст статьи_en'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='text_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст статьи_kg'),
        ),
        migrations.AlterField(
            model_name='creativeproject',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название статьи'),
        ),
        migrations.AlterField(
            model_name='creativeproject',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='formalregistrations',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название статьи'),
        ),
        migrations.AlterField(
            model_name='formalregistrations',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название статьи'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст статьи'),
        ),
    ]
