# Generated by Django 4.0.1 on 2022-04-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeproject',
            name='text_full',
            field=models.TextField(null=True, verbose_name='Полный текст статьи'),
        ),
        migrations.AddField(
            model_name='formalregistrations',
            name='text_full',
            field=models.TextField(null=True, verbose_name='Полный текст статьи'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='text_full',
            field=models.TextField(null=True, verbose_name='Полный текст статьи'),
        ),
    ]
