# Generated by Django 4.0.1 on 2022-04-07 15:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_creativeproject_name_en_creativeproject_name_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст статьи'),
        ),
    ]
