# Generated by Django 4.0.1 on 2022-04-07 16:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_remove_creativeproject_text_full_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
