# Generated by Django 4.0.1 on 2022-04-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_recommendation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeproject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Текст описания'),
        ),
        migrations.AddField(
            model_name='creativeproject',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст описания_en'),
        ),
        migrations.AddField(
            model_name='creativeproject',
            name='description_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст описания_kg'),
        ),
        migrations.AddField(
            model_name='formalregistrations',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Текст описания'),
        ),
        migrations.AddField(
            model_name='formalregistrations',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст описания_en'),
        ),
        migrations.AddField(
            model_name='formalregistrations',
            name='description_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст описания_kg'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Текст описания'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст описания_en'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='description_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст описания_kg'),
        ),
    ]
