# Generated by Django 4.0.1 on 2022-04-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_creativeproject_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Заглавный текст')),
                ('text_kg', models.TextField(blank=True, null=True, verbose_name='Заглавный текст_kg')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Заглавный текст_en')),
            ],
        ),
    ]
