# Generated by Django 4.0.1 on 2022-01-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Название статьи')),
                ('text', models.TextField(verbose_name='Текст татьи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
