# Generated by Django 4.0.1 on 2022-04-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name_en',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название статьи_en'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_kg',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название статьи_kg'),
        ),
        migrations.AddField(
            model_name='event',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст татьи_en'),
        ),
        migrations.AddField(
            model_name='event',
            name='text_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст татьи_kg'),
        ),
    ]
