# Generated by Django 4.0.1 on 2022-03-01 07:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_image_eventimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 1, 7, 26, 42, 650427, tzinfo=utc), verbose_name='Дата проведения'),
            preserve_default=False,
        ),
    ]
